### ISSUE TITLE
How to create custom controls and hotspots in a Next.js project

### ISSUE THREAD

**Issue by pravunathCBD** [mpetroff/pannellum#1146]
I've gone through the section of creating [custom controls](https://pannellum.org/documentation/examples/custom-controls/) and [custom hotspots](https://pannellum.org/documentation/examples/custom-hot-spots/) in the docs but the issue I've been facing is how to implement it in a Next.js project?

I've tried modifying the native styles in my `global.css` file
```css
.pnlm-controls-container {
  position: absolute;
  top: 20px;
  left: 20px;
  z-index: 2;
}
```
But this dosen't seem to work. 

It would be a great help if someone could help me figure out what I'm missing here or how to get this working since I have a project that's dependant on this.
