### ISSUE TITLE
custom hotspot icon image

### ISSUE THREAD

**Issue by d61helix** [mpetroff/pannellum#340]
Hi, I've been try to change the default hotspot icons to custom images based off the example in the docs with the 50x50px with the red background. But nothing shows up. I have really limited knowledge in CSS and I'm probably using a noob approach, is there anything I did wrong? Thanks!

```css
.custom-hotspot {
	height: 50px;
	width: 50px;
	background-image: url(../pano/power.png);
	
}
```
