### ISSUE TITLE
Add CSS Animation to Hot Spots ?

### ISSUE THREAD

**Issue by littlee** [mpetroff/pannellum#440]
my panorama code:
```
window.pannellum.viewer('panorama', {
  type: 'equirectangular',
  panorama: 'images/p.jpg',
  autoLoad: true,
  showZoomCtrl: false,
  showFullscreenCtrl: false,
  compass: false,
  orientationOnByDefault: false,
  minPitch: 0,
  maxPitch: 0,
  minHfov: 60,
  maxHfov: 60,
  hotSpots: [
    {
      pitch: 38,
      yaw: 10,
      cssClass: 'park-hot-spot hs-park-overview',
      clickHandlerFunc: clickHandlerFunc(e, data) {
        var $o = $(data.target)
        $o.css('display', 'block')
        setTimeout(function() {
          $o.addClass('in')
        }, 50)
      },
      clickHandlerArgs: { target: '#page-4-park-overview' }
    }
  ]
})
```
this works fine.

**but** when I want to add css animation to my hot spot, it will always position in the top left corner

```css
.park-hot-spot {
  background-size: 100%;
  background-repeat: no-repeat;
}
.park-hot-spot.hs-park-overview {
  width: 127px;
  height: 95px;
  background-image: url(../images/spot_park_overview.png);
  animation: 3s ease-in-out infinite both anim;
}

@keyframes anim {
  from {
    transform: scale(1);
  }

  25% {
    transform: scale(1.1);
  }

  50% {
    transform: scale(1);
  }

  75% {
    transform: scale(1.1);
  }

  to {
    transform: scale(1);
  }
}
```

Does Pannellum support hot spot css animation ?
