### ISSUE TITLE
Always show tooltip text in hotspot 

### ISSUE THREAD

**Issue by siddharthsinh** [mpetroff/pannellum#578]
Is it possible to always show the tooltip of a hot spot? Currently, there is display on hover. 
I want to change the behaviour to always shown.

**Comment by mpetroff** [comment]
You just need to change the CSS. Adding this to your CSS should work:
```css
div.pnlm-tooltip span {
    visibility: visible !important;
}
```
