### ISSUE TITLE
Auto Scaling Frame

### ISSUE THREAD

**Issue by xlorm** [mpetroff/pannellum#731]
I have been trying to get this panorama frame to scale automatically so as to fit any device but to no avail, is there a way to do this at all or is it unsupported? I have been trying to set it to 100% or auto or even blank under the #panorama tag.
[index.txt](https://github.com/mpetroff/pannellum/files/3195636/index.txt)

**Comment by mpetroff** [comment]
You need to set the size of the root element / body. The following CSS, copied from the standalone viewer, will make the viewer take up the entire page:

```css
html {
    height: 100%;
}
body {
    margin: 0;
    padding: 0;
    overflow: hidden;
    position: fixed;
    cursor: default;
    width: 100%;
    height: 100%;
}
#panorama {
    width: 100%;
    height: 100%;
}
```
